Repository nanoframework/nanoFramework.Json, pull requests merged in 2022-09, with the labels that each got.

#249 Fix running unit tests from within VS
  .runsettings
  azure-pipelines.yml
  nanoFramework.Json.Test/nanoFramework.Json.Test.nfproj
Labels: Area: Config-and-Build, Type: Unit Tests

#247 Performance improvements
  key.snk
  nanoFramework.Json.Benchmark/DeserializationBenchmarks/ReferenceTypesDeserializationBenchmark.cs
  nanoFramework.Json.Benchmark/DeserializationBenchmarks/ValueTypesDeserializationBenchmark.cs
  nanoFramework.Json.Benchmark/SerializationBenchmarks/ReferenceTypesSerializationBenchmark.cs
  nanoFramework.Json.Benchmark/nanoFramework.Json.Benchmark.nfproj
  nanoFramework.Json.Test.Shared/JsonTestClassComplex.cs
  nanoFramework.Json.Test.Shared/JsonTestTown.cs
  nanoFramework.Json.Test/Converters/BoolConverterTests.cs
  nanoFramework.Json.Test/Converters/ByteConverterTests.cs
  nanoFramework.Json.Test/Converters/ConvertersMappingTests.cs
  nanoFramework.Json.Test/Converters/DoubleConverterTests.cs
  nanoFramework.Json.Test/Converters/FloatConverterTests.cs
  nanoFramework.Json.Test/Converters/IntConverterTests.cs
  nanoFramework.Json.Test/Converters/LongConverterTests.cs
  nanoFramework.Json.Test/Converters/SByteConverterTests.cs
  nanoFramework.Json.Test/Converters/ShortConverterTests.cs
  nanoFramework.Json.Test/Converters/StringConverterTests.cs
  nanoFramework.Json.Test/Converters/TimeSpanConverterTests.cs
  nanoFramework.Json.Test/Converters/UIntConverterTests.cs
  nanoFramework.Json.Test/Converters/ULongConverterTests.cs
  nanoFramework.Json.Test/Converters/UShortConverterTests.cs
  nanoFramework.Json.Test/JsonCustomTypeTests.cs
  nanoFramework.Json.Test/JsonUnitTests.cs
  nanoFramework.Json.Test/nanoFramework.Json.Test.nfproj
  nanoFramework.Json/Converters/BoolConverter.cs
  nanoFramework.Json/Converters/ByteConverter.cs
  nanoFramework.Json/Converters/CharConverter.cs
  nanoFramework.Json/Converters/ConvertersMapping.cs
  nanoFramework.Json/Converters/DateTimeConverter.cs
  nanoFramework.Json/Converters/DictionaryEntryConverter.cs
  nanoFramework.Json/Converters/DoubleConverter.cs
  nanoFramework.Json/Converters/FloatConverter.cs
  nanoFramework.Json/Converters/GuidConverter.cs
  nanoFramework.Json/Converters/IConverter.cs
  nanoFramework.Json/Converters/IntConverter.cs
  nanoFramework.Json/Converters/LongConverter.cs
  nanoFramework.Json/Converters/SByteConverter.cs
  nanoFramework.Json/Converters/ShortConverter.cs
  nanoFramework.Json/Converters/StringConverter.cs
  nanoFramework.Json/Converters/TimeSpanConverter.cs
  nanoFramework.Json/Converters/UIntConverter.cs
  nanoFramework.Json/Converters/ULongConverter.cs
  nanoFramework.Json/Converters/UShortConverter.cs
  nanoFramework.Json/JsonConvert.cs
  nanoFramework.Json/JsonSerializer.cs
  nanoFramework.Json/Properties/AssemblyInfo.cs
  nanoFramework.Json/TimeExtensions.cs
  nanoFramework.Json/nanoFramework.Json.nfproj
Labels: Type: enhancement, Type: Unit Tests, ⚠️ DON'T MERGE ⚠️

#250 Clean up unused private/internal methods
  nanoFramework.Json/JsonArray.cs
  nanoFramework.Json/JsonObject.cs
  nanoFramework.Json/JsonProperty.cs
  nanoFramework.Json/JsonToken.cs
  nanoFramework.Json/JsonValue.cs
  nanoFramework.Json/SerializationUtilities.cs
  nanoFramework.Json/nanoFramework.Json.nfproj
Labels: Type: enhancement
